### PR TITLE
[Go]: migrate to gonum.org/v1 packages

### PR DESCRIPTION
**Pull request by acxz**
This is to update go tests so that we can get them up and running in the CI.

Supersedes and closes #27

### CODE REVIEW

**Comment by MilesCranmer** [comment]
Nice work! Looks good to me.

**Comment by MilesCranmer** [comment]
I think @DilumAluthge @giordano @johnfgibson have write access here but am not sure who else. @StefanKarpinski + @ViralBShah look to have merged the most recent code to the go benchmark but not sure if they have bandwidth.

**Comment by ViralBShah** [comment]
Yeah I can take a look. Is this a straightforward merge?

**Comment by acxz** [comment]
@ViralBShah that would be great. At this point, I'd just like to fix up the existing issues with the codebase and keep it up to date with changes such as syntax.

**Comment by DilumAluthge** [comment]
I've added you.

**Comment by acxz** [comment]
Looks like it might take a while for github to register to change, I'll confirm tomorrow morning.

**Comment by DilumAluthge** [comment]
You have to accept the invite manually. Did you get an email from GitHub?

**Comment by acxz** [comment]
As of yet, I have not gotten an email from GitHub.

**Comment by ViralBShah** [comment]
Maybe try here: https://github.com/JuliaLang/Microbenchmarks/invitations

**Comment by acxz** [comment]
I got the following error:

invitation-not-found

**Comment by ViralBShah** [comment]
I think the invite had been sent mistakenly to aczx instead of acxz... Check now.

**Comment by acxz** [comment]
Yep just received it. Thanks!

**Pull request merged**
