### PR TITLE
recursion_fibonacci updated to be Mathematica like

### PR DESCRIPTION
**Pull request by kmisiunas**
Previous implementation of 'recursion_fibonacci' method was C code in Mathematica. Changed it to Mathematica-like implementation wrapped in Module[] to avoid cashing. On my Macbook pro the improvement is 42 times... 

It is even faster if Module[] isolation is not used, but Mathematica does caching of previous results thus it would be not a fair comparison. Read more on: http://community.wolfram.com/groups/-/m/t/442573

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Memoization is cheating since none of the other languages do it, whereas they all could.

**Comment by kmisiunas** [comment]
The proposed version does not do memorisation across different calls. It is inside a Module[]

**Comment by kmisiunas** [comment]
I see your point. Please reject the pull request since Mathematica's recursion is in-fact a lot slower. 

I think the benchmark does not do justice to Mathematica but - at the same time - it is a better performance indicator if one writes complex algorithms from scratch. Anyhow, thanks for your excellent work on Julia!

**Comment by StefanKarpinski** [comment]
It would be interesting to do a comparison of the memoized algorithm version across languages—dead simple, efficient memoization is one of Mathematica's really strong points.

**Pull request closed without merging**
