### PR TITLE
Comp gretl

### PR DESCRIPTION
**Pull request by atecon**
Dear all, I would like to add a benchmark file for the open-source statistics and econometrics software Gretl (URL: http://gretl.sourceforge.net/). This is tested using the latest Gretl release 2018c.

I've added the perf.inp script-file and adapted further changes in the remaining files. I hope this works fine.

Best,
Artur

### CODE REVIEW

**Comment by atecon** [comment]
Hi all, I wondering that nobody has answered on my pull request, yet. Could you please have a look at it?
Thanks!
Best,
Artur

**Comment by StefanKarpinski** [comment]
Hi, thanks for the contribution. I'm afraid that each additional benchmark here adds considerable maintenance burden. We can accept this of @johnfgibson, who has recently taken charge of running the benchmarks is willing to merge and test this. We already have more comparisons than we need.

**Comment by atecon** [comment]
Thanks for your answer, @StefanKarpinski.

@johnfgibson Would you be willing to test the Gretl benchmark in this case? If you need some help with it, please let me know. 

By the way, here is some recent background on the Gretl project ;-)
URL: https://sourceforge.net/blog/january-2019-staff-pick-project-month-gretl/

Best,,
Artur

**Comment by acxz** [comment]
@atecon thanks for the PR.

As @StefanKarpinski previously mentioned adding more and more languages just increases the maintenance burden for us. To ease this burden for us, we have added CI to our pipeline (courtesy of @MilesCranmer) and it would be appropriate to enable your language in our CI code. However, there is a chance that even with those changes we may not want to merge this in as this repo is currently running in maintenance mode. If you would like gretl benchmarks against other languages maybe check out [benchmarksgame](https://salsa.debian.org/benchmarksgame-team/benchmarksgame) and submit a PR to them. To my knowledge that repo is currently the most active benchmark suite.

Considering this is a stale PR and @johnfgibson has not responded either, I'll go ahead and close this PR.
If anyone disagrees with this, please comment and we can open this PR back up.

We apologize for the late response.

**Pull request closed without merging**
